# Generated by Django 3.2.5 on 2021-07-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20210719_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='disctrict',
            new_name='district',
        ),
    ]
