# Generated by Django 3.2.5 on 2021-07-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_rename_disctrict_donor_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactivate', 'deactivate')], default='deactivate', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
