# Generated by Django 3.2.5 on 2021-07-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_auto_20210719_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='district',
            field=models.CharField(blank=True, choices=[('Comilla', 'Comilla'), ('Feni', 'Feni'), ('Brahmanbaria', 'Brahmanbaria'), ('Rangamati', 'Rangamati'), ('Noakhali', 'Noakhali'), ('Chandpur', 'Chandpur'), ('Lakshmipur', 'Lakshmipur'), ('Chattogram', 'Chattogram'), ('Coxsbazar', 'Coxsbazar'), ('Khagrachhari', 'Khagrachhari'), ('Bandarban', 'Bandarban'), ('Sirajganj', 'Sirajganj'), ('Pabna', 'Pabna'), ('Bogura', 'Bogura'), ('Rajshahi', 'Rajshahi'), ('Natore', 'Natore'), ('Joypurhat', 'Joypurhat'), ('Chapainawabganj', 'Chapainawabganj'), ('Naogaon', 'Naogaon'), ('Jashore', 'Jashore'), ('Satkhira', 'Satkhira'), ('Meherpur', 'Meherpur'), ('Narail', 'Narail'), ('Chuadanga', 'Chuadanga'), ('Kushtia', 'Kushtia'), ('Magura', 'Magura'), ('Khulna', 'Khulna'), ('Bagerhat', 'Bagerhat'), ('Jhenaidah', 'Jhenaidah'), ('Jhalakathi', 'Jhalakathi'), ('Patuakhali', 'Patuakhali'), ('Pirojpur', 'Pirojpur'), ('Barisal', 'Barisal'), ('Bhola', 'Bhola'), ('Barguna', 'Barguna'), ('Sylhet', 'Sylhet'), ('Moulvibazar', 'Moulvibazar'), ('Habiganj', 'Habiganj'), ('Sunamganj', 'Sunamganj'), ('Narsingdi', 'Narsingdi'), ('Gazipur', 'Gazipur'), ('Shariatpur', 'Shariatpur'), ('Narayanganj', 'Narayanganj'), ('Tangail', 'Tangail'), ('Kishoreganj', 'Kishoreganj'), ('Manikganj', 'Manikganj'), ('Dhaka', 'Dhaka'), ('Munshiganj', 'Munshiganj'), ('Rajbari', 'Rajbari'), ('Madaripur', 'Madaripur'), ('Gopalganj', 'Gopalganj'), ('Faridpur', 'Faridpur'), ('Panchagarh', 'Panchagarh'), ('Dinajpur', 'Dinajpur'), ('Lalmonirhat', 'Lalmonirhat'), ('Nilphamari', 'Nilphamari'), ('Thakurgaon', 'Thakurgaon'), ('Rangpur', 'Rangpur'), ('Kurigram', 'Kurigram'), ('Sherpur', 'Sherpur'), ('Mymensingh', 'Mymensingh'), ('Jamalpur', 'Jamalpur'), ('Netrokona', 'Netrokona')], max_length=100),
        ),
    ]
