# Generated by Django 3.2.5 on 2022-03-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_alter_donor_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='union',
            field=models.CharField(blank=True, choices=[('চরতী', 'চরতী'), ('খাগরিয়া', 'খাগরিয়া'), ('নলুয়া', 'নলুয়া'), ('কাঞ্চনা', 'কাঞ্চনা'), ('অমিলাইশ', 'অমিলাইশ'), ('এওচিয়া', 'এওচিয়া'), ('মাদারশা', 'মাদারশা'), ('ঢেমশা', 'ঢেমশা'), ('পশ্চিম ঢেমশা', 'পশ্চিম ঢেমশা'), ('কেঁওচিয়া', 'কেঁওচিয়া'), ('কালিয়াইশ', 'কালিয়াইশ'), ('বাজালিয়া', 'বাজালিয়া'), ('পুরানগড়', 'পুরানগড়'), ('ছদাহা', 'ছদাহা'), ('সাতকানিয়া', 'সাতকানিয়া'), ('সোনাকানিয়া', 'সোনাকানিয়া'), ('সাতকানিয়া সদর', 'সাতকানিয়া সদর')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='ward_no',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='district',
            field=models.CharField(blank=True, choices=[('Chattogram', 'Chattogram')], max_length=100, null=True),
        ),
    ]
