# Generated by Django 3.2.5 on 2022-03-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_auto_20220318_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='sub_district',
            field=models.CharField(blank=True, choices=[('সাতকানিয়া', 'সাতকানিয়া'), ('সীতাকুন্ড', 'সীতাকুন্ড'), ('মীরসরাই', 'মীরসরাই'), ('পটিয়া', 'পটিয়া'), ('পটিয়া', 'পটিয়া'), ('সন্দ্বীপ', 'সন্দ্বীপ'), ('বাঁশখালী', 'বাঁশখালী'), ('বোয়ালখালী', 'বোয়ালখালী'), ('আনোয়ারা', 'আনোয়ারা'), ('চন্দনাইশ', 'চন্দনাইশ'), ('রাঙ্গুনিয়া', 'রাঙ্গুনিয়া'), ('লোহাগাড়া', 'লোহাগাড়া'), ('হাটহাজারী', 'হাটহাজারী'), ('ফটিকছড়ি', 'ফটিকছড়ি'), ('রাউজান', 'রাউজান'), ('কর্ণফুলী', 'কর্ণফুলী')], max_length=100, null=True),
        ),
    ]
