# Generated by Django 3.2.5 on 2022-03-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_surukotha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=250)),
                ('picture', models.ImageField(upload_to='media/volunteers/')),
                ('fb_link', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=13)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
