# Generated by Django 3.2.5 on 2022-03-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0013_adviser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='adviser/'),
        ),
    ]
