# Generated by Django 3.2.5 on 2022-03-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_shohojogi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shohojogi',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shohojogi',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
